PROMPT="===========================================================
[%M] %10c (%?) $ "

setopt completealiases
setopt append_history
setopt share_history
setopt histignorealldups
setopt nobeep
setopt interactivecomments

zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list '' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'r:|[._-:=]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' max-errors 5 numeric
zstyle ':completion:*' menu select
zstyle :compinstall filename '/home/vk/.zshrc'

autoload -Uz compinit
compinit
HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=1000000
setopt appendhistory autocd extendedglob
bindkey -v

autoload edit-command-line; zle -N edit-command-line
bindkey -M vicmd v edit-command-line

bindkey '\e[3~' delete-char
bindkey '^R' history-incremental-search-backward

# Spelling mistaeks happen.
alias v='vim -p'
alias c='vim -p'
alias nin='ninja'
alias ninha='ninja'
alias l='ls'
alias sl='ls'

# Git.
alias g='git'
alias gst='git status'
alias gco='git checkout'
alias gcp='git cherry-pick'
alias squash='git commit --amend -C @'
alias gg='git grep'

# Grab the first column of the input, using ":" as the column separator.
alias fst='cut -d":" -f1 | uniq | grep -vE "\.pyc$|Binary "'

# Edit files matching a git-grep search.
edit() { v $(gg -l $*) }

# Edit a file found with fzf.
editf() { v $(fzf) }

# Move to a directory found with fzf.
cdf() { cd $(dirname $(fzf)) }

llvm_build_dir() {
  src_dir=$(pwd | grep -Eo "$HOME/src/[^/]+")
  src_label=$(basename $src_dir)
  echo "$HOME/src/builds/$src_label-$1"
}

# Move to the build directory corresponding to the current source directory.
cdb() {
  cd $(llvm_build_dir $1)
}

# Return the source directory corresponding to the current build directory.
# Optionally drill down into a source subdirectory specified in $1.
srcs() {
  build_dir=$(pwd | grep -Eo "$HOME/src/builds/[^/]+")
  src_label=$(basename $build_dir | sed -E 's/-(R|D)A?//g' | sed -E 's/-(SAN|stage2|all)//g')
  src_dir="$HOME/src/$src_label"
  echo "$src_dir/$1"
}

# Move to the source directory corresponding to the current build directory.
cds() { cd $(srcs $*) }

configure_monorepo() {
  build_dir=$(llvm_build_dir $1)
  mkdir -p $build_dir || return
  cd $build_dir
  src_dir=$(srcs llvm)
  llvm_cmake_configure="xcrun cmake -G Ninja $src_dir -DCLANG_ENABLE_ARCMT=Off -DCLANG_ENABLE_STATIC_ANALYZER=Off -DLLVM_ENABLE_PROJECTS='clang;libcxx;libcxxabi;compiler-rt;libunwind'"
  if [[ "$1" == "RA" ]]; then
     llvm_cmake_configure="$llvm_cmake_configure -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=On"
  elif [[ "$1" == "R" ]]; then
     llvm_cmake_configure="$llvm_cmake_configure -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=Off"
  elif [[ "$1" == "D" ]]; then
     llvm_cmake_configure="$llvm_cmake_configure -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_ASSERTIONS=On"
  else
    echo "Don't know how to configure $1."
    rm -rf $build_dir
    return
  fi
  eval "$llvm_cmake_configure"
}

# Print out SIL function decls along with SIL debug locations.
sil_locations() { grep -Eo 'sil [^@]*@[^ ]+|loc "[^"]+":\d+:\d+' $* | sed -E 's/"[^"]+"://g' }

# Sum the numbers in a column of input.
sumcol() { awk "{ sum += \$$1 } END { print sum }" }

# Average the numbers in a column of input.
avgcol() {
	awk -f ~/scripts/avg.awk -v col=$1
}

# Pretty-print "squashed" JSON read from stdin. Removes Python `u` Unicode prefixes.
ppjson() { python -c "import json, pprint; pprint.pprint(json.loads(raw_input()))" | sed -E "s/u'([^']*)'/ '\1'/g" }

# Apple buildit.
alias rcbuild='~rc/bin/buildit'

# Handling remote sessions.
alias ssh="caffeinate ssh"
alias tmux="caffeinate tmux -2"
alias t="tmux"
alias ta="tmux attach -t"
alias clip="nc localhost 8377"
alias agent='eval $(keychain --eval --agents ssh -Q --quiet id_rsa)'

# System settings.

# Core files.
# ulimit -c unlimited

# Need to increase the open file limit.
ulimit -n 2048

export EDITOR=vim
export EMAIL=vsk@apple.com
export REPLYTO=$EMAIL

export PATH=~/scripts:$PATH
export PATH=~/int_zorg/tests/clang_qa/utils/:$PATH
export PATH=~/src/llvm-project-master/llvm/utils/git-svn/:$PATH
export PATH=/opt/distcc-r796/bin:$PATH
